# theme: jekyll-theme-minimal
# title: Kurt Su's person blog
# description: This is Kurt Su's personal blog. I just created it and plan to write some math, programming related content on it. Thank you for visiting this site. Hope you had a good time. :-)
